<a href="https://colab.research.google.com/github/lcato061/AB-testing/blob/main/A_B_C_D_landing_page.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install kaggle
!kaggle datasets download -d feeldidaxie/landing-page-abcd-testing-dataset
!unzip /content/landing-page-abcd-testing-dataset.zip

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.0)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.15 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.16)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.2.25)
Dataset URL: https://www.kaggle.com/datasets/feeldidaxie/landing-page-abcd-testing-dataset
License(s): CC0-1.0
landing-page-abcd-testing-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)
Archive:  /content/landing-page-abcd-testing-dataset.zip
  inflating: four_sessions.csv

In [ ]:
import pandas as pd
df=pd.read_csv('/content/four_sessions.csv')
print(df.head())

     Page  Time
0  Page 1   164
1  Page 2   178
2  Page 3   175
3  Page 4   155
4  Page 1   172

In [ ]:
df.info()
df.describe()
df.isna().sum()
df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Page    20 non-null     object
 1   Time    20 non-null     int64
dtypes: int64(1), object(1)
memory usage: 452.0+ bytes

np.int64(0)

In [ ]:
dupes=df[df.duplicated()]
print(dupes)

Empty DataFrame
Columns: [Page, Time]
Index: []

In [ ]:
df['Page'].value_counts()

Page
Page 1    5
Page 2    5
Page 3    5
Page 4    5
Name: count, dtype: int64

In [ ]:
df[df['Page']=='Page 1'].describe()
df[df['Page']=='Page 2'].describe()
df[df['Page']=='Page 3'].describe()
df[df['Page']=='Page 4'].describe()

             Time
count    5.000000
mean   164.600000
std      5.813777
min    155.000000
25%    164.000000
50%    166.000000
75%    168.000000
max    170.000000

In [ ]:
conversion_rates = df.groupby('Page')['Time'].mean()
print(conversion_rates)

Page
Page 1    172.8
Page 2    182.6
Page 3    175.6
Page 4    164.6
Name: Time, dtype: float64

In [ ]:
import numpy as np

page1_time = df[df['Page'] == 'Page 1']['Time']
page2_time = df[df['Page'] == 'Page 2']['Time']
page3_time = df[df['Page'] == 'Page 3']['Time']
page4_time = df[df['Page'] == 'Page 4']['Time']

counts = np.array([len(page1_time), len(page2_time), len(page3_time), len(page4_time)])
means = np.array([page1_time.mean(), page2_time.mean(), page3_time.mean(), page4_time.mean()])
counts, means

(array([5, 5, 5, 5]), array([172.8, 182.6, 175.6, 164.6]))

In [ ]:
from scipy.stats import f_oneway

# Perform ANOVA test
f_statistic, p_value = f_oneway(page1_time, page2_time, page3_time, page4_time)

print(f"F-statistic: {f_statistic:.2f}")
print(f"P-value: {p_value:.3f}")

if p_value < 0.05:
    print("There is a statistically significant difference between the mean times on the pages.")
else:
    print("There is no statistically significant difference between the mean times on the pages.")

F-statistic: 2.74
P-value: 0.078
There is no statistically significant difference between the mean times on the pages.